name: Birthday Email Sender

on:
  workflow_dispatch:   # manual run
  schedule:
    - cron: "0 3 * * *"   # runs daily (UTC) → ~8:30 AM India

jobs:
  send-email:
    runs-on: ubuntu-latest

    env:
      MY_EMAIL: ${{ secrets.MY_EMAIL }}
      MY_PASSWORD: ${{ secrets.MY_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas python-dotenv

      - name: Run birthday script
        run: python main.py

      - name: Run birthday wisher
        run: python main.py
